# Menú principal (cabecera), ordenado por weight.
[[main]]
  name = "About"
  pageRef = "about"
  weight = 10

[[main]]
  name = "Resume"
  pageRef = "resume"
  weight = 20

[[main]]
  name = "Publications"
  pageRef = "publications"
  weight = 30

[[main]]
  name = "Posts"
  pageRef = "posts"
  weight = 40

[[main]]
  name = "Projects"
  pageRef = "projects"
  weight = 50

# Menú del pie de página.
[[footer]]
  name = "Tags"
  pageRef = "tags"
  weight = 10
